# Permalinks
permalink:           posts/:categories/:title

# Setup
title:               Wicked Good Data
description:         'Quantitative Psychology PhD and Data Scientist at Boston Medical Center.'
url:                 http://dpmartin42.github.io
baseurl:             ''
highlighter:         rouge

# About/contact
author:
  name:              Dan Martin
  email:             dpmartin42@gmail.com

# Plugins 
plugins:
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from

# Set up google analytics

analytics :
  provider : google
  google : 
      tracking_id : 'UA-123-12'
  getclicky :
    site_id : UA-26032429-1

# Custom vars
version:             1.0.0
